### ISSUE TITLE
I would like to test this application as a service within Rancher.

### ISSUE THREAD

**Issue by MichelDiz** [etlweather/gaucho#24]
I'll do my tests, but an "official" hint of the maintainer would be a good one.

```yml
rancher-gaucho:
  labels:
    io.rancher.container.create_agent: 'true'
    io.rancher.container.agent.role: environment
  image: etlweather/gaucho
```

**Comment by etlweather** [comment]
Hi there, unfortunately, I don't totally understand what hint you would like... or question you have. 

What you have written there are the correct labels. That makes Rancher automatically put the necessary environment variables inside the container with the URL, username and password to use to connect to the API.

You will need to put in whatever command you would like to run. The entrypoint is the binary, so you would just put the parameters in the CMD, as shown in the readme:

```
docker run --rm -it etlweather/gaucho query 1s245
```

If you wanted to use this as a build pipeline or something of the sort, you may need to make your own container with additional things. 

For example, the way I use it is I run a simple webhook server (https://github.com/adnanh/webhook) and my build pipeline simply cURL the appropriate URL that then runs Gaucho to call the appropriate Rancher APIs.

**Comment by MichelDiz** [comment]
Yes, my intention is to make Gaucho part of a stage of gitlab-ci.yml

I wanted to leave the Gaucho as an internal Rancher service as part of the infrastructure. Just so you do not have to deal with CLI all the time.

I intended that Gaucho only update a container (which will do an action) and after that container it would update a second container containing a NodeJS instance.

**Comment by MichelDiz** [comment]
YML would look like this, thanks.

```yml
version: '2'
services:
  rancher-gaucho:
    image: etlweather/gaucho
    command:
    - query
    - 1a5
    labels:
      io.rancher.container.agent.role: environment
      io.rancher.container.create_agent: 'true'

```
